import type { Metadata } from "next";
import "./globals.css";

import { Header } from "./components/Header";
import QueryProvider from "./components/QueryProvider";

import { NuqsAdapter } from "nuqs/adapters/next/app";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans bg-radial from-fuchsia-400 from-0% to-fuchsia-950 to-100% min-h-screen">
        <QueryProvider>
          <NuqsAdapter>
            <Header />
            {children}
          </NuqsAdapter>
        </QueryProvider>
      </body>
    </html>
  );
}
